#!/bin/sh

set -ev

# MINICONDA=Miniconda3-latest-MacOSX-x86_64.sh
# wget http://repo.continuum.io/miniconda/${MINICONDA} -O miniconda.sh
# bash miniconda.sh -b -p ${HOME}/miniconda
# source "$HOME/miniconda/etc/profile.d/conda.sh"
# 
# hash -r
# 
# conda config --set always_yes yes --set changeps1 no
# conda update -q conda
# conda info -a

conda create --name odil -c conda-forge -c bioconda \
  boost cmake dcmtk icu jsoncpp ninja pkg-config pybind11
