#!/bin/sh

set -ev

export Python=${Python:?}
export WORKSPACE=${WORKSPACE:?}

mkdir build
mkdir install
cd build

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig

cmake \
  -D CMAKE_INSTALL_PREFIX="${WORKSPACE}/install" \
  -D PYTHON_EXECUTABLE=/usr/local/opt/python@2/bin/python2.7 \
  -D PYTHON_INCLUDE_DIR=/usr/include/python2.7 \
  -D PYTHON_LIBRARY=/usr/lib/libpython2.7.dylib \
  ${CMAKE_OPTIONS} \
  ..
make ${MAKE_OPTIONS} install
