#!/bin/sh

set -ev

export Python=${Python:?}
export WORKSPACE=${WORKSPACE:?}

BREW_CONFLICTING="json-c"
# FIXME: this does not install the Python 3 version of boost-python
BREW_NEED_LATEST="boost boost-python cmake cppcheck dcmtk icu4c jsoncpp lcov log4cpp pkg-config python${Python}"
PIP_PACKAGES="cpp-coveralls nose"

brew install jq

for formula in ${BREW_CONFLICTING}; do
  if ! (brew info ${formula} | grep -q "Not installed"); then
    brew unlink ${formula}
  fi
done

for formula in ${BREW_NEED_LATEST}; do
  if (brew outdated | grep -q ${formula}); then
    brew upgrade ${formula}
  else
    brew install ${formula}
  fi
done

pip${Python} install -U ${PIP_PACKAGES}
