#!/bin/sh

set -ev

export Python=${Python:?}
export WORKSPACE=${WORKSPACE:?}

cd build

if [ "${Python}" = "2" ]
then
  PYTHON_VERSION="$(pyversions -dv)"
elif [ "${Python}" = "3" ]
then
  PYTHON_VERSION="$(py3versions -dv)"
else
  PYTHON_VERSION="UNKOWN"
fi

export PYTHONPATH=${WORKSPACE}/install/lib/python${PYTHON_VERSION}/site-packages/
../tests/run --no-network --nose ~/Library/Python/${Python}*/bin/nosetests
