#!/bin/sh

set -ev

export Python=${Python:?}
export WORKSPACE=${WORKSPACE:?}

cd build

PYTHON_EXECUTABLE="/usr/local/bin/python${Python}"
PYTHON_VERSION="$(${PYTHON_EXECUTABLE} -c 'import sys;print(sys.version[:3])')"
LOCAL_PYTHON_PREFIX="$(${PYTHON_EXECUTABLE} -c 'from distutils.sysconfig import *; print(get_python_lib(True, prefix=str()))')"

export PYTHONPATH=${WORKSPACE}/install/${LOCAL_PYTHON_PREFIX}
export PATH=~/Library/Python/${PYTHON_VERSION}/bin:${PATH}
../tests/run --no-network --nose nosetests-${PYTHON_VERSION}
