#!/bin/sh

set -ev

export Architecture=${Architecture:?}
export Distribution=${Distribution:?}
export Python=${Python:?}
export WORKSPACE=${WORKSPACE:?}

if [ "${Python}" = "2" ]
then
  PYTHON_VERSION="$(pyversions -dv)"
elif [ "${Python}" = "3" ]
then
  PYTHON_VERSION="$(py3versions -dv)"
else
  PYTHON_VERSION="UNKOWN"
fi

cd ${WORKSPACE}

mkdir -p build
mkdir -p install
cd build
cmake \
  -D CMAKE_INSTALL_PREFIX="${WORKSPACE}/install" \
  -D PYTHON_EXECUTABLE=/usr/bin/python${PYTHON_VERSION} \
  ${CMAKE_OPTIONS} \
  ..
make ${MAKE_OPTIONS} install
