#!/bin/sh

set -ev

export Python=${Python:?}

apt-get -y update
apt-get -y --no-install-recommends install gnupg software-properties-common wget
wget -O - http://dl.bintray.com/lamyj/generic/gpg.key | apt-key add -
add-apt-repository "deb http://dl.bintray.com/lamyj/generic/apt $(lsb_release -cs) main"

if [ "${Python}" = "2" ]
then
  PYTHON_PREFIX="python"
elif [ "${Python}" = "3" ]
then
  PYTHON_PREFIX="python3"
fi

# Compilation toolchain
PACKAGES="build-essential cmake pkg-config python-minimal"
# Dependencies of main lib
PACKAGES="${PACKAGES} libboost-dev libboost-date-time-dev "
PACKAGES="${PACKAGES} libboost-log-dev libboost-filesystem-dev"
PACKAGES="${PACKAGES} libdcmtk2-dev libicu-dev libjsoncpp-dev zlib1g-dev"
# Dependencies of Python wrappers
PACKAGES="${PACKAGES} pybind11-dev ${PYTHON_PREFIX}-pybind11 ${PYTHON_PREFIX}-dev"
# Dependencies of unit tests
PACKAGES="${PACKAGES} dcmtk libboost-test-dev ${PYTHON_PREFIX}-nose"

apt-get -y update
apt-get -y --no-install-recommends install ${PACKAGES}
