#!/bin/sh

set -ev

apt-get update
apt-get -y --no-install-recommends install apt-transport-https curl gnupg \
  software-properties-common unzip wget

REPOSITORY=https://iris-packages.s3.unistra.fr
wget -O - ${REPOSITORY}/gpg.key | apt-key add -
if wget -q -O /dev/null ${REPOSITORY}/apt/dists/$(lsb_release -cs)/Release; then
  add-apt-repository "deb ${REPOSITORY}/apt $(lsb_release -cs) main"
fi
apt-get update

apt-get -y --no-install-recommends install \
  build-essential cmake ninja-build pkg-config python3 \
  libboost-dev libboost-date-time-dev libboost-exception-dev \
  libboost-log-dev libboost-filesystem-dev libboost-regex-dev \
  libdcmtk2-dev libicu-dev libjsoncpp-dev zlib1g-dev \
  pybind11-dev python3-pybind11 python3-dev \
  libboost-test-dev dcmtk
